export const TOP_FRANCHISES = [
  // --- Original set ---
  { id: "call-of-duty", name: "Call of Duty", emoji: "🎖️", color: "#1a1a2e", accent: "#e94560", genre: "FPS" },
  { id: "minecraft", name: "Minecraft", emoji: "⛏️", color: "#2d5a27", accent: "#7cb342", genre: "Sandbox" },
  { id: "gta", name: "Grand Theft Auto", emoji: "🚗", color: "#1a1a1a", accent: "#fcb045", genre: "Open World" },
  { id: "valorant", name: "Valorant", emoji: "🔫", color: "#0f1923", accent: "#ff4655", genre: "FPS" },
  { id: "fortnite", name: "Fortnite", emoji: "🏗️", color: "#0a1929", accent: "#00d4ff", genre: "Battle Royale" },
  { id: "nba2k", name: "NBA 2K", emoji: "🏀", color: "#1a1a2e", accent: "#f85f36", genre: "Sports" },
  { id: "fifa", name: "EA FC / FIFA", emoji: "⚽", color: "#0d3349", accent: "#00d2ff", genre: "Sports" },
  { id: "madden-nfl", name: "Madden NFL", emoji: "🏈", color: "#1a2a1a", accent: "#00843d", genre: "Sports" },
  { id: "wwe2k", name: "WWE 2K", emoji: "🤼", color: "#1a0a0a", accent: "#ffd700", genre: "Wrestling" },
  { id: "ufc", name: "UFC", emoji: "🥊", color: "#1a0a0a", accent: "#e63946", genre: "Fighting" },
  { id: "mario", name: "Super Mario", emoji: "🍄", color: "#c0392b", accent: "#f39c12", genre: "Platformer" },
  { id: "zelda", name: "Legend of Zelda", emoji: "🗡️", color: "#1a2a0a", accent: "#27ae60", genre: "Adventure" },
  { id: "pokemon", name: "Pokémon", emoji: "⚡", color: "#1a1a0a", accent: "#f4d03f", genre: "RPG" },
  { id: "league-of-legends", name: "League of Legends", emoji: "🏆", color: "#0a1a2a", accent: "#c89b3c", genre: "MOBA" },
  { id: "dota2", name: "Dota 2", emoji: "🔮", color: "#1a0a2a", accent: "#a855f7", genre: "MOBA" },
  { id: "pubg", name: "PUBG", emoji: "🪂", color: "#1a1400", accent: "#f0a500", genre: "Battle Royale" },
  { id: "apex-legends", name: "Apex Legends", emoji: "💥", color: "#1a0a0a", accent: "#ff6b35", genre: "Battle Royale" },
  { id: "overwatch", name: "Overwatch 2", emoji: "🦸", color: "#0a1a2a", accent: "#fa9c1e", genre: "Hero Shooter" },
  { id: "rocket-league", name: "Rocket League", emoji: "🚀", color: "#0a0a2a", accent: "#4fc3f7", genre: "Sports" },
  { id: "among-us", name: "Among Us", emoji: "🔴", color: "#1a0a1a", accent: "#e91e63", genre: "Social" },
  { id: "fall-guys", name: "Fall Guys", emoji: "🫘", color: "#2a1a0a", accent: "#ff9800", genre: "Party" },
  { id: "roblox", name: "Roblox", emoji: "🧱", color: "#1a1a1a", accent: "#e53935", genre: "Sandbox" },
  { id: "destiny2", name: "Destiny 2", emoji: "🌌", color: "#0a0a1a", accent: "#6a1de8", genre: "FPS" },
  { id: "halo", name: "Halo", emoji: "🪖", color: "#0a1a1a", accent: "#00bcd4", genre: "FPS" },
  { id: "god-of-war", name: "God of War", emoji: "⚔️", color: "#2a0a0a", accent: "#c0392b", genre: "Action" },
  { id: "spider-man", name: "Spider-Man", emoji: "🕷️", color: "#1a0a2a", accent: "#e53935", genre: "Action" },
  { id: "mortal-kombat", name: "Mortal Kombat", emoji: "💀", color: "#1a0a0a", accent: "#f44336", genre: "Fighting" },
  { id: "street-fighter", name: "Street Fighter", emoji: "👊", color: "#1a0a0a", accent: "#3f51b5", genre: "Fighting" },
  { id: "tekken", name: "Tekken", emoji: "🥋", color: "#0a0a1a", accent: "#2196f3", genre: "Fighting" },
  { id: "elden-ring", name: "Elden Ring", emoji: "💫", color: "#1a1400", accent: "#c8a84b", genre: "RPG" },
  { id: "dark-souls", name: "Dark Souls", emoji: "🔥", color: "#1a0a0a", accent: "#ff6f00", genre: "RPG" },
  { id: "witcher", name: "The Witcher", emoji: "🐺", color: "#1a1400", accent: "#8bc34a", genre: "RPG" },
  { id: "cyberpunk", name: "Cyberpunk 2077", emoji: "🌆", color: "#0a0a1a", accent: "#f7e716", genre: "RPG" },
  { id: "last-of-us", name: "The Last of Us", emoji: "🍄", color: "#0a1a0a", accent: "#8bc34a", genre: "Adventure" },
  { id: "red-dead", name: "Red Dead Redemption", emoji: "🤠", color: "#1a0a00", accent: "#bf360c", genre: "Open World" },
  { id: "battlefield", name: "Battlefield", emoji: "💣", color: "#1a1200", accent: "#ff8f00", genre: "FPS" },
  { id: "rainbow-six", name: "Rainbow Six Siege", emoji: "🛡️", color: "#0a1a1a", accent: "#00bcd4", genre: "Tactical" },
  { id: "warzone", name: "Warzone", emoji: "☠️", color: "#0a0a1a", accent: "#78909c", genre: "Battle Royale" },
  { id: "mlb-show", name: "MLB The Show", emoji: "⚾", color: "#0a1a2a", accent: "#1565c0", genre: "Sports" },
  { id: "diablo", name: "Diablo", emoji: "👹", color: "#1a0000", accent: "#b71c1c", genre: "RPG" },
  { id: "world-of-warcraft", name: "World of Warcraft", emoji: "⚔️", color: "#0a0a2a", accent: "#33691e", genre: "MMO" },
  { id: "final-fantasy", name: "Final Fantasy", emoji: "💎", color: "#0a0a1a", accent: "#7986cb", genre: "RPG" },
  { id: "dragon-ball", name: "Dragon Ball FighterZ", emoji: "⚡", color: "#1a0a00", accent: "#ff9100", genre: "Fighting" },
  { id: "naruto-storm", name: "Naruto Storm", emoji: "🌀", color: "#1a0800", accent: "#ff6d00", genre: "Fighting" },
  { id: "genshin", name: "Genshin Impact", emoji: "🌸", color: "#0a0a1a", accent: "#ab47bc", genre: "RPG" },

  // --- RPG Expansion ---
  { id: "skyrim", name: "Skyrim", emoji: "🐉", color: "#1a1a2e", accent: "#6dd5ed", genre: "RPG" },
  { id: "fallout", name: "Fallout", emoji: "☢️", color: "#1a1400", accent: "#a3e635", genre: "RPG" },
  { id: "mass-effect", name: "Mass Effect", emoji: "🌌", color: "#0a1a2a", accent: "#3b82f6", genre: "RPG" },
  { id: "dragon-age", name: "Dragon Age", emoji: "🐲", color: "#2a0a0a", accent: "#dc2626", genre: "RPG" },
  { id: "starfield", name: "Starfield", emoji: "🌠", color: "#0a0a1a", accent: "#818cf8", genre: "RPG" },
  { id: "baldurs-gate", name: "Baldur's Gate", emoji: "⚗️", color: "#0a1a0a", accent: "#7c3aed", genre: "RPG" },
  { id: "divinity-os", name: "Divinity: Original Sin", emoji: "🧙", color: "#1a0a1a", accent: "#f59e0b", genre: "RPG" },
  { id: "persona", name: "Persona", emoji: "🎭", color: "#1a0a0a", accent: "#e11d48", genre: "RPG" },
  { id: "final-fantasy-xiv", name: "Final Fantasy XIV", emoji: "🗡️", color: "#0a0a1a", accent: "#38bdf8", genre: "MMO" },
  { id: "monster-hunter", name: "Monster Hunter", emoji: "🦕", color: "#1a0a00", accent: "#ea580c", genre: "Action RPG" },
  { id: "dragons-dogma", name: "Dragon's Dogma", emoji: "🏰", color: "#1a1a0a", accent: "#ca8a04", genre: "Action RPG" },
  { id: "kingdom-hearts", name: "Kingdom Hearts", emoji: "🔑", color: "#1a0a2a", accent: "#818cf8", genre: "Action RPG" },
  { id: "horizon", name: "Horizon Zero Dawn", emoji: "🤖", color: "#0a1a1a", accent: "#facc15", genre: "Action RPG" },
  { id: "ghost-of-tsushima", name: "Ghost of Tsushima", emoji: "🌸", color: "#1a0a0a", accent: "#f43f5e", genre: "Action" },
  { id: "fable", name: "Fable", emoji: "🧚", color: "#0a1a0a", accent: "#4ade80", genre: "RPG" },
  { id: "suikoden", name: "Suikoden", emoji: "🏯", color: "#1a0a0a", accent: "#c084fc", genre: "RPG" },
  { id: "tales-of-arise", name: "Tales of Arise", emoji: "🌺", color: "#1a0a0a", accent: "#fb7185", genre: "RPG" },
  { id: "star-ocean", name: "Star Ocean", emoji: "🛸", color: "#0a0a1a", accent: "#60a5fa", genre: "RPG" },
  { id: "xenoblade", name: "Xenoblade Chronicles", emoji: "⚙️", color: "#0a1a2a", accent: "#a78bfa", genre: "RPG" },
  { id: "yakuza", name: "Yakuza / Like a Dragon", emoji: "🐉", color: "#1a0a0a", accent: "#fbbf24", genre: "Action RPG" },
  { id: "hollow-knight", name: "Hollow Knight", emoji: "🦋", color: "#0a0a1a", accent: "#c4b5fd", genre: "Metroidvania" },
  { id: "octopath", name: "Octopath Traveler", emoji: "🎨", color: "#1a1400", accent: "#fde68a", genre: "RPG" },
  { id: "fire-emblem", name: "Fire Emblem", emoji: "🔥", color: "#1a0a0a", accent: "#ef4444", genre: "Strategy RPG" },
  { id: "ni-no-kuni", name: "Ni no Kuni", emoji: "✨", color: "#0a1a2a", accent: "#67e8f9", genre: "RPG" },
  { id: "wasteland", name: "Wasteland", emoji: "🌵", color: "#1a0a00", accent: "#d97706", genre: "RPG" },

  // --- FPS / Tactical ---
  { id: "far-cry", name: "Far Cry", emoji: "🌴", color: "#0a1a0a", accent: "#f97316", genre: "FPS" },
  { id: "bioshock", name: "BioShock", emoji: "🌊", color: "#0a1a2a", accent: "#06b6d4", genre: "FPS" },
  { id: "half-life", name: "Half-Life", emoji: "🔬", color: "#0a1a0a", accent: "#f59e0b", genre: "FPS" },
  { id: "doom", name: "Doom", emoji: "💀", color: "#1a0000", accent: "#ef4444", genre: "FPS" },
  { id: "wolfenstein", name: "Wolfenstein", emoji: "🏴", color: "#1a1a1a", accent: "#dc2626", genre: "FPS" },
  { id: "quake", name: "Quake", emoji: "⚡", color: "#1a0a00", accent: "#f97316", genre: "FPS" },
  { id: "unreal-tournament", name: "Unreal Tournament", emoji: "🎯", color: "#0a0a1a", accent: "#a78bfa", genre: "FPS" },
  { id: "titanfall", name: "Titanfall", emoji: "🤖", color: "#0a1a2a", accent: "#60a5fa", genre: "FPS" },
  { id: "metro", name: "Metro", emoji: "🚇", color: "#1a1a0a", accent: "#a3e635", genre: "FPS" },
  { id: "stalker", name: "STALKER", emoji: "☢️", color: "#0a1a0a", accent: "#84cc16", genre: "FPS" },
  { id: "tarkov", name: "Escape from Tarkov", emoji: "🎒", color: "#1a1a1a", accent: "#78716c", genre: "Tactical" },
  { id: "insurgency", name: "Insurgency", emoji: "🪖", color: "#1a1a0a", accent: "#92400e", genre: "Tactical" },
  { id: "squad", name: "Squad", emoji: "🗺️", color: "#0a1a0a", accent: "#16a34a", genre: "Tactical" },
  { id: "arma", name: "Arma", emoji: "🎖️", color: "#0a1a0a", accent: "#65a30d", genre: "Tactical" },
  { id: "crysis", name: "Crysis", emoji: "🔬", color: "#0a1a0a", accent: "#22d3ee", genre: "FPS" },
  { id: "left4dead", name: "Left 4 Dead", emoji: "🧟", color: "#1a0000", accent: "#dc2626", genre: "Co-op FPS" },
  { id: "payday", name: "Payday", emoji: "💰", color: "#1a0a0a", accent: "#f59e0b", genre: "Co-op FPS" },
  { id: "killing-floor", name: "Killing Floor", emoji: "🔪", color: "#1a0000", accent: "#b91c1c", genre: "Co-op FPS" },
  { id: "superhot", name: "Superhot", emoji: "🕶️", color: "#1a0000", accent: "#ef4444", genre: "FPS" },
  { id: "fear", name: "F.E.A.R.", emoji: "👁️", color: "#1a0000", accent: "#dc2626", genre: "FPS" },
  { id: "prey", name: "Prey", emoji: "🔭", color: "#0a0a1a", accent: "#818cf8", genre: "FPS" },
  { id: "system-shock", name: "System Shock", emoji: "🤖", color: "#0a0a1a", accent: "#22d3ee", genre: "FPS" },
  { id: "bulletstorm", name: "Bulletstorm", emoji: "💥", color: "#1a0a00", accent: "#f97316", genre: "FPS" },
  { id: "rage", name: "Rage", emoji: "😡", color: "#1a0a00", accent: "#f97316", genre: "FPS" },

  // --- Strategy / Simulation ---
  { id: "age-of-empires", name: "Age of Empires", emoji: "🏰", color: "#1a1400", accent: "#ca8a04", genre: "Strategy" },
  { id: "civilization", name: "Civilization", emoji: "🌍", color: "#0a1a0a", accent: "#16a34a", genre: "Strategy" },
  { id: "starcraft", name: "StarCraft", emoji: "🛸", color: "#0a0a1a", accent: "#60a5fa", genre: "Strategy" },
  { id: "warcraft", name: "Warcraft", emoji: "⚔️", color: "#0a1a0a", accent: "#4ade80", genre: "Strategy" },
  { id: "total-war", name: "Total War", emoji: "⚔️", color: "#1a1400", accent: "#b45309", genre: "Strategy" },
  { id: "hearts-of-iron", name: "Hearts of Iron", emoji: "🗺️", color: "#1a1a0a", accent: "#dc2626", genre: "Strategy" },
  { id: "stellaris", name: "Stellaris", emoji: "🌌", color: "#0a0a1a", accent: "#818cf8", genre: "Strategy" },
  { id: "cities-skylines", name: "Cities: Skylines", emoji: "🏙️", color: "#0a1a2a", accent: "#38bdf8", genre: "Simulation" },
  { id: "the-sims", name: "The Sims", emoji: "🏠", color: "#0a1a0a", accent: "#4ade80", genre: "Simulation" },
  { id: "factorio", name: "Factorio", emoji: "🏭", color: "#1a1a0a", accent: "#f97316", genre: "Strategy" },
  { id: "rimworld", name: "RimWorld", emoji: "🌍", color: "#1a1400", accent: "#d97706", genre: "Strategy" },
  { id: "stardew-valley", name: "Stardew Valley", emoji: "🌾", color: "#0a1a0a", accent: "#86efac", genre: "Simulation" },
  { id: "animal-crossing", name: "Animal Crossing", emoji: "🌳", color: "#0a1a0a", accent: "#bbf7d0", genre: "Simulation" },
  { id: "farming-simulator", name: "Farming Simulator", emoji: "🚜", color: "#0a1a0a", accent: "#84cc16", genre: "Simulation" },
  { id: "euro-truck", name: "Euro Truck Simulator", emoji: "🚛", color: "#0a1a2a", accent: "#60a5fa", genre: "Simulation" },
  { id: "flight-sim", name: "Microsoft Flight Simulator", emoji: "✈️", color: "#0a1a2a", accent: "#38bdf8", genre: "Simulation" },
  { id: "anno", name: "Anno", emoji: "⚓", color: "#0a1a2a", accent: "#06b6d4", genre: "Strategy" },
  { id: "crusader-kings", name: "Crusader Kings", emoji: "👑", color: "#1a1400", accent: "#f59e0b", genre: "Strategy" },
  { id: "xcom", name: "XCOM", emoji: "👽", color: "#0a1a0a", accent: "#22c55e", genre: "Strategy" },
  { id: "company-of-heroes", name: "Company of Heroes", emoji: "🪖", color: "#1a1400", accent: "#ca8a04", genre: "Strategy" },
  { id: "dawn-of-war", name: "Dawn of War", emoji: "🔴", color: "#1a0000", accent: "#dc2626", genre: "Strategy" },
  { id: "command-conquer", name: "Command & Conquer", emoji: "🏗️", color: "#0a1a0a", accent: "#f97316", genre: "Strategy" },
  { id: "tropico", name: "Tropico", emoji: "🌴", color: "#0a1a0a", accent: "#fbbf24", genre: "Simulation" },
  { id: "planet-coaster", name: "Planet Coaster", emoji: "🎢", color: "#0a1a2a", accent: "#f472b6", genre: "Simulation" },
  { id: "prison-architect", name: "Prison Architect", emoji: "🏛️", color: "#1a1a1a", accent: "#94a3b8", genre: "Simulation" },

  // --- Horror / Survival ---
  { id: "resident-evil", name: "Resident Evil", emoji: "🧟", color: "#1a0000", accent: "#dc2626", genre: "Horror" },
  { id: "silent-hill", name: "Silent Hill", emoji: "🌫️", color: "#1a1a1a", accent: "#94a3b8", genre: "Horror" },
  { id: "dead-space", name: "Dead Space", emoji: "🔴", color: "#0a0a1a", accent: "#ef4444", genre: "Horror" },
  { id: "alan-wake", name: "Alan Wake", emoji: "🔦", color: "#0a0a1a", accent: "#fde68a", genre: "Horror" },
  { id: "outlast", name: "Outlast", emoji: "📷", color: "#1a0000", accent: "#dc2626", genre: "Horror" },
  { id: "amnesia", name: "Amnesia", emoji: "🕯️", color: "#1a1a0a", accent: "#78716c", genre: "Horror" },
  { id: "phasmophobia", name: "Phasmophobia", emoji: "👻", color: "#0a0a1a", accent: "#818cf8", genre: "Horror" },
  { id: "subnautica", name: "Subnautica", emoji: "🌊", color: "#0a1a2a", accent: "#06b6d4", genre: "Survival" },
  { id: "dayz", name: "DayZ", emoji: "🧟", color: "#1a1400", accent: "#84cc16", genre: "Survival" },
  { id: "rust", name: "Rust", emoji: "🔩", color: "#1a0a00", accent: "#f97316", genre: "Survival" },
  { id: "ark", name: "ARK: Survival Evolved", emoji: "🦕", color: "#0a1a0a", accent: "#4ade80", genre: "Survival" },
  { id: "the-forest", name: "The Forest", emoji: "🌲", color: "#0a1a0a", accent: "#16a34a", genre: "Survival" },
  { id: "dying-light", name: "Dying Light", emoji: "🧟", color: "#0a1a0a", accent: "#84cc16", genre: "Horror" },
  { id: "dead-island", name: "Dead Island", emoji: "🏝️", color: "#0a1a0a", accent: "#f97316", genre: "Horror" },
  { id: "until-dawn", name: "Until Dawn", emoji: "❄️", color: "#0a0a1a", accent: "#818cf8", genre: "Horror" },
  { id: "bloodborne", name: "Bloodborne", emoji: "🩸", color: "#1a0000", accent: "#b91c1c", genre: "Action RPG" },
  { id: "evil-within", name: "Evil Within", emoji: "👁️", color: "#1a0000", accent: "#dc2626", genre: "Horror" },
  { id: "little-nightmares", name: "Little Nightmares", emoji: "🕯️", color: "#1a1400", accent: "#fde68a", genre: "Horror" },
  { id: "signalis", name: "Signalis", emoji: "📡", color: "#0a0a1a", accent: "#f43f5e", genre: "Horror" },
  { id: "darkest-dungeon", name: "Darkest Dungeon", emoji: "🕯️", color: "#1a0000", accent: "#dc2626", genre: "RPG" },
  { id: "project-zomboid", name: "Project Zomboid", emoji: "🧟", color: "#1a1400", accent: "#84cc16", genre: "Survival" },
  { id: "raft", name: "Raft", emoji: "🪵", color: "#0a1a2a", accent: "#38bdf8", genre: "Survival" },
  { id: "grounded", name: "Grounded", emoji: "🐛", color: "#0a1a0a", accent: "#84cc16", genre: "Survival" },
  { id: "dont-starve", name: "Don't Starve", emoji: "🕯️", color: "#1a1a1a", accent: "#fde68a", genre: "Survival" },
  { id: "valheim", name: "Valheim", emoji: "⚡", color: "#0a0a1a", accent: "#818cf8", genre: "Survival" },

  // --- Special Requests ---
  { id: "pes-football-life", name: "PES / Football Life", emoji: "⚽", color: "#0a1a0a", accent: "#22c55e", genre: "Sports",
    subgames: ["PES 6", "PES 2013", "PES 2017", "PES 2021", "Football Life", "PPSSPP/PSP/PS2"] },
  { id: "counter-strike", name: "Counter Strike", emoji: "💣", color: "#1a1a2e", accent: "#f4a722", genre: "FPS" },
  { id: "nfs-special", name: "Need for Speed", emoji: "🏎️", color: "#0a0a1a", accent: "#00bfa5", genre: "Racing" },
  { id: "james-bond", name: "007 James Bond", emoji: "🔫", color: "#1a1a1a", accent: "#d4af37", genre: "Action" },
  { id: "hitman", name: "Hitman", emoji: "🎯", color: "#1a1a1a", accent: "#dc2626", genre: "Stealth" },
  { id: "assassins-creed", name: "Assassin's Creed", emoji: "🦅", color: "#0a0a1a", accent: "#f5f5f5", genre: "Action" },
  { id: "forza", name: "Forza Horizon", emoji: "🚘", color: "#0a1a2a", accent: "#29b6f6", genre: "Racing" },
];