// 200+ world languages with native names, codes, and RTL flags
export const LANGUAGES = [
  { code: "en", name: "English", native: "English", rtl: false },
  { code: "zh-TW", name: "Traditional Chinese", native: "繁體中文", rtl: false },
  { code: "zh-CN", name: "Simplified Chinese", native: "简体中文", rtl: false },
  { code: "ar", name: "Arabic", native: "العربية", rtl: true },
  { code: "es", name: "Spanish", native: "Español", rtl: false },
  { code: "fr", name: "French", native: "Français", rtl: false },
  { code: "de", name: "German", native: "Deutsch", rtl: false },
  { code: "ja", name: "Japanese", native: "日本語", rtl: false },
  { code: "ko", name: "Korean", native: "한국어", rtl: false },
  { code: "pt", name: "Portuguese", native: "Português", rtl: false },
  { code: "ru", name: "Russian", native: "Русский", rtl: false },
  { code: "hi", name: "Hindi", native: "हिन्दी", rtl: false },
  { code: "it", name: "Italian", native: "Italiano", rtl: false },
  { code: "nl", name: "Dutch", native: "Nederlands", rtl: false },
  { code: "pl", name: "Polish", native: "Polski", rtl: false },
  { code: "tr", name: "Turkish", native: "Türkçe", rtl: false },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", rtl: false },
  { code: "th", name: "Thai", native: "ภาษาไทย", rtl: false },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", rtl: false },
  { code: "ms", name: "Malay", native: "Bahasa Melayu", rtl: false },
  { code: "fa", name: "Persian", native: "فارسی", rtl: true },
  { code: "he", name: "Hebrew", native: "עברית", rtl: true },
  { code: "ur", name: "Urdu", native: "اردو", rtl: true },
  { code: "bn", name: "Bengali", native: "বাংলা", rtl: false },
  { code: "ta", name: "Tamil", native: "தமிழ்", rtl: false },
  { code: "te", name: "Telugu", native: "తెలుగు", rtl: false },
  { code: "mr", name: "Marathi", native: "मराठी", rtl: false },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", rtl: false },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", rtl: false },
  { code: "ml", name: "Malayalam", native: "മലയാളം", rtl: false },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", rtl: false },
  { code: "si", name: "Sinhala", native: "සිංහල", rtl: false },
  { code: "ne", name: "Nepali", native: "नेपाली", rtl: false },
  { code: "my", name: "Burmese", native: "မြန်မာဘာသာ", rtl: false },
  { code: "km", name: "Khmer", native: "ភាសាខ្មែរ", rtl: false },
  { code: "lo", name: "Lao", native: "ພາສາລາວ", rtl: false },
  { code: "ka", name: "Georgian", native: "ქართული", rtl: false },
  { code: "hy", name: "Armenian", native: "Հայերեն", rtl: false },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan", rtl: false },
  { code: "kk", name: "Kazakh", native: "Қазақша", rtl: false },
  { code: "uz", name: "Uzbek", native: "Oʻzbek", rtl: false },
  { code: "tk", name: "Turkmen", native: "Türkmen", rtl: false },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча", rtl: false },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ", rtl: false },
  { code: "mn", name: "Mongolian", native: "Монгол", rtl: false },
  { code: "uk", name: "Ukrainian", native: "Українська", rtl: false },
  { code: "be", name: "Belarusian", native: "Беларуская", rtl: false },
  { code: "bg", name: "Bulgarian", native: "Български", rtl: false },
  { code: "sr", name: "Serbian", native: "Српски", rtl: false },
  { code: "hr", name: "Croatian", native: "Hrvatski", rtl: false },
  { code: "bs", name: "Bosnian", native: "Bosanski", rtl: false },
  { code: "sl", name: "Slovenian", native: "Slovenščina", rtl: false },
  { code: "sk", name: "Slovak", native: "Slovenčina", rtl: false },
  { code: "cs", name: "Czech", native: "Čeština", rtl: false },
  { code: "ro", name: "Romanian", native: "Română", rtl: false },
  { code: "hu", name: "Hungarian", native: "Magyar", rtl: false },
  { code: "fi", name: "Finnish", native: "Suomi", rtl: false },
  { code: "et", name: "Estonian", native: "Eesti", rtl: false },
  { code: "lv", name: "Latvian", native: "Latviešu", rtl: false },
  { code: "lt", name: "Lithuanian", native: "Lietuvių", rtl: false },
  { code: "sv", name: "Swedish", native: "Svenska", rtl: false },
  { code: "no", name: "Norwegian", native: "Norsk", rtl: false },
  { code: "da", name: "Danish", native: "Dansk", rtl: false },
  { code: "is", name: "Icelandic", native: "Íslenska", rtl: false },
  { code: "ga", name: "Irish", native: "Gaeilge", rtl: false },
  { code: "cy", name: "Welsh", native: "Cymraeg", rtl: false },
  { code: "eu", name: "Basque", native: "Euskara", rtl: false },
  { code: "ca", name: "Catalan", native: "Català", rtl: false },
  { code: "gl", name: "Galician", native: "Galego", rtl: false },
  { code: "af", name: "Afrikaans", native: "Afrikaans", rtl: false },
  { code: "sq", name: "Albanian", native: "Shqip", rtl: false },
  { code: "mk", name: "Macedonian", native: "Македонски", rtl: false },
  { code: "el", name: "Greek", native: "Ελληνικά", rtl: false },
  { code: "la", name: "Latin", native: "Latina", rtl: false },
  { code: "mt", name: "Maltese", native: "Malti", rtl: false },
  { code: "sw", name: "Swahili", native: "Kiswahili", rtl: false },
  { code: "am", name: "Amharic", native: "አማርኛ", rtl: false },
  { code: "so", name: "Somali", native: "Soomaali", rtl: false },
  { code: "ha", name: "Hausa", native: "Hausa", rtl: false },
  { code: "yo", name: "Yoruba", native: "Yorùbá", rtl: false },
  { code: "ig", name: "Igbo", native: "Igbo", rtl: false },
  { code: "zu", name: "Zulu", native: "isiZulu", rtl: false },
  { code: "xh", name: "Xhosa", native: "isiXhosa", rtl: false },
  { code: "st", name: "Sesotho", native: "Sesotho", rtl: false },
  { code: "sn", name: "Shona", native: "chiShona", rtl: false },
  { code: "ny", name: "Chichewa", native: "Chichewa", rtl: false },
  { code: "mg", name: "Malagasy", native: "Malagasy", rtl: false },
  { code: "rw", name: "Kinyarwanda", native: "Kinyarwanda", rtl: false },
  { code: "ln", name: "Lingala", native: "Lingála", rtl: false },
  { code: "kg", name: "Kongo", native: "Kikongo", rtl: false },
  { code: "ak", name: "Akan", native: "Akan", rtl: false },
  { code: "ee", name: "Ewe", native: "Eʋegbe", rtl: false },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ", rtl: false },
  { code: "om", name: "Oromo", native: "Afaan Oromoo", rtl: false },
  { code: "wo", name: "Wolof", native: "Wolof", rtl: false },
  { code: "ber", name: "Berber", native: "ⵜⴰⵎⴰⵣⵉⵖⵜ", rtl: false },
  { code: "fil", name: "Filipino", native: "Filipino", rtl: false },
  { code: "ceb", name: "Cebuano", native: "Cebuano", rtl: false },
  { code: "ilo", name: "Ilocano", native: "Ilocano", rtl: false },
  { code: "tl", name: "Tagalog", native: "Tagalog", rtl: false },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi", rtl: false },
  { code: "sm", name: "Samoan", native: "Gagana Samoa", rtl: false },
  { code: "to", name: "Tongan", native: "Lea faka-Tonga", rtl: false },
  { code: "fj", name: "Fijian", native: "Vosa Vakaviti", rtl: false },
  { code: "mi", name: "Maori", native: "Te Reo Māori", rtl: false },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan", rtl: false },
  { code: "ps", name: "Pashto", native: "پښتو", rtl: true },
  { code: "sd", name: "Sindhi", native: "سنڌي", rtl: true },
  { code: "ku", name: "Kurdish", native: "Kurdî", rtl: true },
  { code: "ckb", name: "Central Kurdish", native: "کوردیی ناوەندی", rtl: true },
  { code: "dv", name: "Dhivehi", native: "ދިވެހި", rtl: true },
  { code: "ug", name: "Uyghur", native: "ئۇيغۇرچە", rtl: true },
  { code: "tk", name: "Turkmen", native: "Türkmen", rtl: false },
  { code: "hy", name: "Armenian", native: "Հայերեն", rtl: false },
  { code: "jv", name: "Javanese", native: "Basa Jawa", rtl: false },
  { code: "su", name: "Sundanese", native: "Basa Sunda", rtl: false },
  { code: "min", name: "Minangkabau", native: "Minangkabau", rtl: false },
  { code: "bug", name: "Buginese", native: "ᨅᨔ ᨕᨘᨁᨗ", rtl: false },
  { code: "ban", name: "Balinese", native: "Basa Bali", rtl: false },
  { code: "mad", name: "Madurese", native: "Bhâsa Madhurâ", rtl: false },
  { code: "ace", name: "Acehnese", native: "Acèh", rtl: false },
  { code: "sat", name: "Santali", native: "ᱥᱟᱱᱛᱟᱲᱤ", rtl: false },
  { code: "mai", name: "Maithili", native: "मैथिली", rtl: false },
  { code: "bho", name: "Bhojpuri", native: "भोजपुरी", rtl: false },
  { code: "mag", name: "Magahi", native: "मगही", rtl: false },
  { code: "doi", name: "Dogri", native: "डोगरी", rtl: false },
  { code: "kok", name: "Konkani", native: "कोंकणी", rtl: false },
  { code: "as", name: "Assamese", native: "অসমীয়া", rtl: false },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ", rtl: false },
  { code: "sa", name: "Sanskrit", native: "संस्कृतम्", rtl: false },
  { code: "bo", name: "Tibetan", native: "བོད་ཡིག", rtl: false },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ", rtl: false },
  { code: "tn", name: "Setswana", native: "Setswana", rtl: false },
  { code: "ss", name: "Swati", native: "siSwati", rtl: false },
  { code: "ts", name: "Tsonga", native: "Xitsonga", rtl: false },
  { code: "ve", name: "Venda", native: "Tshivenḓa", rtl: false },
  { code: "nr", name: "Southern Ndebele", native: "isiNdebele", rtl: false },
  { code: "nd", name: "Northern Ndebele", native: "isiNdebele", rtl: false },
  { code: "nso", name: "Northern Sotho", native: "Sesotho sa Leboa", rtl: false },
  { code: "ff", name: "Fula", native: "Fulfulde", rtl: false },
  { code: "bm", name: "Bambara", native: "Bamanankan", rtl: false },
  { code: "dyu", name: "Dyula", native: "Julakan", rtl: false },
  { code: "sg", name: "Sango", native: "Sängö", rtl: false },
  { code: "bi", name: "Bislama", native: "Bislama", rtl: false },
  { code: "to", name: "Tonga", native: "Lea faka-Tonga", rtl: false },
  { code: "qu", name: "Quechua", native: "Runa Simi", rtl: false },
  { code: "ay", name: "Aymara", native: "Aymar aru", rtl: false },
  { code: "gn", name: "Guarani", native: "Avañe'ẽ", rtl: false },
  { code: "nah", name: "Nahuatl", native: "Nāhuatl", rtl: false },
  { code: "yi", name: "Yiddish", native: "ייִדיש", rtl: true },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch", rtl: false },
  { code: "br", name: "Breton", native: "Brezhoneg", rtl: false },
  { code: "oc", name: "Occitan", native: "Occitan", rtl: false },
  { code: "co", name: "Corsican", native: "Corsu", rtl: false },
  { code: "sc", name: "Sardinian", native: "Sardu", rtl: false },
  { code: "fur", name: "Friulian", native: "Furlan", rtl: false },
  { code: "rm", name: "Romansh", native: "Rumantsch", rtl: false },
  { code: "gsw", name: "Alemannic", native: "Alemannisch", rtl: false },
  { code: "vec", name: "Venetian", native: "Vèneto", rtl: false },
  { code: "lij", name: "Ligurian", native: "Ligure", rtl: false },
  { code: "nap", name: "Neapolitan", native: "Napulitano", rtl: false },
  { code: "scn", name: "Sicilian", native: "Sicilianu", rtl: false },
  { code: "szl", name: "Silesian", native: "Ślōnskŏ", rtl: false },
  { code: "csb", name: "Kashubian", native: "Kaszëbsczi", rtl: false },
  { code: "hsb", name: "Upper Sorbian", native: "Hornjoserbsce", rtl: false },
  { code: "dsb", name: "Lower Sorbian", native: "Dolnoserbski", rtl: false },
  { code: "bua", name: "Buryat", native: "Буряад хэлэн", rtl: false },
  { code: "sah", name: "Sakha", native: "Саха тыла", rtl: false },
  { code: "chv", name: "Chuvash", native: "Чӑваш чӗлхи", rtl: false },
  { code: "cv", name: "Chuvash", native: "Чӑвашла", rtl: false },
  { code: "tt", name: "Tatar", native: "Татарча", rtl: false },
  { code: "ba", name: "Bashkir", native: "Башҡортса", rtl: false },
  { code: "udm", name: "Udmurt", native: "Удмурт", rtl: false },
  { code: "kv", name: "Komi", native: "Коми", rtl: false },
  { code: "mrj", name: "Western Mari", native: "Олыкмарий", rtl: false },
  { code: "mhr", name: "Eastern Mari", native: "Марий", rtl: false },
  { code: "mdf", name: "Moksha", native: "Мокшень", rtl: false },
  { code: "myv", name: "Erzya", native: "Эрзянь", rtl: false },
  { code: "krl", name: "Karelian", native: "Karjala", rtl: false },
  { code: "vep", name: "Veps", native: "Vepsän kel'", rtl: false },
  { code: "olo", name: "Livvi-Karelian", native: "Livvinkarjala", rtl: false },
  { code: "fkv", name: "Kven", native: "Kväänin kieli", rtl: false },
  { code: "sme", name: "Northern Sami", native: "Davvisámegiella", rtl: false },
  { code: "smj", name: "Lule Sami", native: "Julevsámegiella", rtl: false },
  { code: "sms", name: "Skolt Sami", native: "Sääʹmǩiõll", rtl: false },
  { code: "se", name: "Sami", native: "Sámegiella", rtl: false },
  { code: "fo", name: "Faroese", native: "Føroyskt", rtl: false },
  { code: "kl", name: "Greenlandic", native: "Kalaallisut", rtl: false },
  { code: "iu", name: "Inuktitut", native: "ᐃᓄᒃᑎᑐᑦ", rtl: false },
  { code: "cr", name: "Cree", native: "ᓀᐦᐃᔭᐍᐏᐣ", rtl: false },
  { code: "oj", name: "Ojibwe", native: "ᐊᓂᔑᓈᐯᒧᐎᓐ", rtl: false },
  { code: "nv", name: "Navajo", native: "Diné bizaad", rtl: false },
  { code: "chr", name: "Cherokee", native: "ᏣᎳᎩ", rtl: false },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi", rtl: false },
  { code: "rap", name: "Rapa Nui", native: "Vananga Rapa Nui", rtl: false },
  { code: "tet", name: "Tetum", native: "Tetun", rtl: false },
  { code: "mh", name: "Marshallese", native: "Kajin M̧ajeļ", rtl: false },
  { code: "kj", name: "Kuanyama", native: "Kuanyama", rtl: false },
  { code: "lua", name: "Luba-Kasai", native: "Tshiluba", rtl: false },
  { code: "umb", name: "Umbundu", native: "Umbundu", rtl: false },
  { code: "kmb", name: "Kimbundu", native: "Kimbundu", rtl: false },
  { code: "tn", name: "Tswana", native: "Setswana", rtl: false },
];

// Country code → language code mapping for auto-detection
export const COUNTRY_TO_LANG = {
  TW: "zh-TW", HK: "zh-TW", MO: "zh-TW",
  CN: "zh-CN", SG: "zh-CN",
  SA: "ar", AE: "ar", QA: "ar", KW: "ar", BH: "ar", OM: "ar",
  JO: "ar", LB: "ar", SY: "ar", IQ: "ar", EG: "ar", LY: "ar",
  TN: "ar", MA: "ar", DZ: "ar", SD: "ar", YE: "ar", PS: "ar",
  ES: "es", MX: "es", CO: "es", AR: "es", CL: "es", PE: "es",
  VE: "es", EC: "es", BO: "es", PY: "es", UY: "es", CR: "es",
  PA: "es", DO: "es", HN: "es", SV: "es", GT: "es", CU: "es", NI: "es",
  FR: "fr", BE: "fr", CH: "fr", LU: "fr", MC: "fr",
  DE: "de", AT: "de",
  JP: "ja",
  KR: "ko",
  BR: "pt", PT: "pt",
  RU: "ru", BY: "ru",
  IN: "hi",
  IT: "it",
  NL: "nl",
  PL: "pl",
  TR: "tr",
  VN: "vi",
  TH: "th",
  ID: "id",
  MY: "ms",
  IR: "fa",
  IL: "he",
  PK: "ur",
  BD: "bn",
  PH: "fil",
  UA: "uk",
  GR: "el",
  CZ: "cs",
  SK: "sk",
  HU: "hu",
  RO: "ro",
  BG: "bg",
  HR: "hr",
  RS: "sr",
  SI: "sl",
  FI: "fi",
  EE: "et",
  LV: "lv",
  LT: "lt",
  SE: "sv",
  NO: "no",
  DK: "da",
  IS: "is",
  MN: "mn",
  MM: "my",
  KH: "km",
  LA: "lo",
  GE: "ka",
  AM: "hy",
  AZ: "az",
  KZ: "kk",
  UZ: "uz",
  KG: "ky",
  TJ: "tg",
  AF: "ps",
  NP: "ne",
  LK: "si",
  ET: "am",
  NG: "yo",
  KE: "sw",
  TZ: "sw",
  UG: "sw",
  ZA: "zu",
  GH: "ak",
  CM: "fr",
  CI: "fr",
  SN: "wo",
  ML: "bm",
  BF: "fr",
  NE: "fr",
  TD: "fr",
  CF: "sg",
  CD: "ln",
  CG: "fr",
  GA: "fr",
  GQ: "es",
  AO: "pt",
  MZ: "pt",
  CV: "pt",
  ST: "pt",
  MR: "ar",
  ER: "ti",
  SO: "so",
  DJ: "fr",
  RW: "rw",
  BI: "rw",
  MW: "ny",
  ZM: "en",
  ZW: "sn",
  BW: "tn",
  NA: "af",
  SZ: "ss",
  LS: "st",
  MG: "mg",
  MU: "fr",
  SC: "fr",
  KM: "ar",
  NZ: "mi",
  FJ: "fj",
  WS: "sm",
  TO: "to",
  US: "en", CA: "en", GB: "en", AU: "en", IE: "en",
  AL: "sq", MK: "mk", MT: "mt", CY: "el",
  LB: "ar", MX: "es", EC: "es",
  TM: "tk", MV: "dv",
  BT: "dz", TL: "tet",
  SS: "en", ER: "ti",
};

export function getLanguageByCode(code) {
  return LANGUAGES.find(l => l.code === code) || LANGUAGES[0];
}