name = "gamer-productions-api"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "gamerproductionsmedia"
[vars]
R2_PUBLIC_URL = "https://media.gamer.productions"
