import React from "react";
import ManagedAccountsPanel from "@/components/admin/ManagedAccountsPanel";
import { useAuth } from "@/lib/AuthContext";
import { Navigate } from "react-router-dom";

export default function CreatedAccountsPage() {
  const { user, isLoadingAuth } = useAuth();
  const MASTER_EMAIL = "kevinarnold522@gmail.com";

  if (isLoadingAuth) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="w-8 h-8 border-4 border-purple-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  // 🛡️ BRUTE FORCE FALLBACK ACCESS CONTROL
  // Extracting email from all possible nested object formats generated by Base44 builder
  const currentEmail = user?.email || user?.attributes?.email || user?.primaryEmail || "";
  const currentRole = user?.role || "";

  const isMasterAdmin = currentEmail.toLowerCase() === MASTER_EMAIL.toLowerCase();
  const hasAdminRole = currentRole === 'admin';

  // ❌ If they are not you AND they don't have an admin flag, block the component instantly!
  if (!isMasterAdmin && !hasAdminRole) {
    return <Navigate to="/dashboard" replace />;
  }

  // ✅ Only your master account gets past the gate to load the panels and user lists
  return (
    <div className="min-h-screen bg-gray-950">
      <ManagedAccountsPanel />
    </div>
  );
}
